# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c054e396b81f2ab84c84c0d9214699a49b2ca786c72bd99125f867ccb9b435945427bb46d802e89586774c8a161f45b1d49e9c20e56d3cf681078944e531da

test:
  secret_key_base: 4e34722711c1471708935416857e73772808ff55df2b533091ded93c972d04613f22cb68a2a4f9299b43e94c65dd638459bcc6975f5f491e450a319e3e870b44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
